OMNIA_PLATFORM = "omnia"
OMNIA_CONFIG_PATH = "./config/omnia.ini"


M7_PLATFORM = "vgd"
M7_CONFIG_PATH = "./config/vgd.ini"


MASTER_MODE_FULL = "full"


PLATFORM_LIST = (OMNIA_PLATFORM, M7_PLATFORM)
MODE_LIST = (MASTER_MODE_FULL,)


BUSY_STATE = "busy"
FREE_STATE = "free"
SECTION_ADDRESS = "ADDRESS"
SECTION_STATUS = "STATUS"
SECTION_INFO = "INFO"
